const cat=document.getElementById('cat'),bubble=document.getElementById('catBubble'),room=document.getElementById('roomScene'),roomWrap=document.querySelector('.room-wrap');
const pauseButton=document.getElementById('pauseButton'),lightButton=document.getElementById('lightButton'),soundButton=document.getElementById('soundButton');
let paused=false,pos={x:52,y:73},step=0,bubbleTimer,clickCount=0;
const stops=[{x:52,y:73},{x:43,y:74},{x:32,y:73},{x:40,y:74},{x:59,y:72},{x:70,y:73},{x:62,y:75}];
function speak(message,duration=2200){bubble.textContent=message;bubble.classList.add('show');clearTimeout(bubbleTimer);bubbleTimer=setTimeout(()=>bubble.classList.remove('show'),duration)}
function move(x,y){if(paused)return;cat.style.setProperty('--flip',x<pos.x?'-1':'1');cat.style.setProperty('--cat-x',`${x}%`);cat.style.setProperty('--cat-y',`${y}%`);pos={x,y}}
function setPause(value){paused=value;cat.classList.toggle('paused',value);pauseButton.setAttribute('aria-pressed',String(value));pauseButton.setAttribute('aria-label',value?'고양이 산책 계속하기':'고양이 산책 멈추기');pauseButton.innerHTML=value?'▶ <span>다시 걷기</span>':'Ⅱ <span>산책 멈추기</span>';cat.setAttribute('aria-label',value?'탐정 고양이. 누르면 다시 걷습니다.':'탐정 고양이. 누르면 걸음을 멈춥니다.');speak(value?'잠깐 쉴게!':'다시 출발!')}
cat.addEventListener('click',()=>{clickCount++;setPause(!paused);if(clickCount===3)speak('모자 안에는 비밀이 없어. 아마도?',3000)});
pauseButton.addEventListener('click',()=>setPause(!paused));
lightButton.addEventListener('click',()=>{const lit=roomWrap.classList.toggle('lit');lightButton.setAttribute('aria-pressed',String(lit));lightButton.setAttribute('aria-label',lit?'기본 조명으로 돌아가기':'조명 밝히기');lightButton.innerHTML=lit?'☾ <span>기본 조명</span>':'☼ <span>조명 밝히기</span>'});
if(window.matchMedia('(hover:hover) and (pointer:fine)').matches){room.addEventListener('pointermove',e=>{const r=room.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;room.style.setProperty('--ry',`${(-x*3).toFixed(2)}deg`);room.style.setProperty('--rx',`${(y*2).toFixed(2)}deg`)});room.addEventListener('pointerleave',()=>{room.style.setProperty('--ry','0deg');room.style.setProperty('--rx','0deg')})}
let audioCtx,soundOn=false,audioTimer,note=0;
function tone(frequency,time,duration,volume){const oscillator=audioCtx.createOscillator(),gain=audioCtx.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(volume,time+.05);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);oscillator.connect(gain).connect(audioCtx.destination);oscillator.start(time);oscillator.stop(time+duration+.05)}
function melody(){const notes=[261.63,329.63,392,329.63,293.66,261.63,220,261.63,293.66,349.23,329.63,293.66,261.63,220,196,220],t=audioCtx.currentTime;tone(notes[note%notes.length],t,.85,.014);if(note%4===0)tone([130.81,110,98,110][Math.floor(note/4)%4],t,2.7,.009);note++}
soundButton.addEventListener('click',async()=>{soundOn=!soundOn;if(soundOn){try{audioCtx ||=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume();melody();audioTimer=setInterval(melody,820)}catch{soundOn=false;speak('이 브라우저에선 음악을 켤 수 없어요.')}}else{clearInterval(audioTimer);await audioCtx?.suspend()}soundButton.setAttribute('aria-pressed',String(soundOn));soundButton.setAttribute('aria-label',soundOn?'배경 음악 끄기':'배경 음악 켜기');soundButton.querySelector('span').textContent=soundOn?'SOUND ON':'SOUND OFF'});
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(()=>{if(paused)return;step=(step+1)%stops.length;move(stops[step].x,stops[step].y)},3500);
setTimeout(()=>speak('어서 와!',2500),600);
