const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const key = 'dohyun-pixel-room-v1';
const initial = {todos:[],notes:'',events:{},links:[{title:'Google Calendar',url:'https://calendar.google.com/calendar/u/0/r'},{title:'ChatGPT',url:'https://chatgpt.com/'},{title:'내 GitHub',url:'https://github.com/sherlock0105'}]};
let saved;try{saved=JSON.parse(localStorage.getItem(key))||{}}catch{saved={}}
const state={...initial,...saved,todos:Array.isArray(saved.todos)?saved.todos:[],events:saved.events&&typeof saved.events==='object'?saved.events:{},links:Array.isArray(saved.links)?saved.links:initial.links};
function persist(){try{localStorage.setItem(key,JSON.stringify(state))}catch{}}
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function selectTab(name){$$('.tab').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',active)});$$('.panel-view').forEach(p=>{const active=p.dataset.view===name;p.classList.toggle('active',active);p.hidden=!active});if(name==='calendar')renderCalendar()}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>{selectTab(b.dataset.open);if(innerWidth<1031)$('.side-panel').scrollIntoView({behavior:'smooth',block:'start'})}));$$('.tab').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));
function clock(){const now=new Date();$('#clock').textContent=new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(now);$('#date').textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(now)}clock();setInterval(clock,10000);
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}});
function renderTodos(){const list=$('#todo-list');list.replaceChildren();const completed=state.todos.filter(t=>t.done).length;$('#todo-count').textContent=`${completed} / ${state.todos.length}`;if(!state.todos.length){const p=document.createElement('p');p.className='empty';p.textContent='게시판이 비어 있어요. 첫 할 일을 추가해 보세요.';list.append(p);return}state.todos.forEach(t=>{const row=document.createElement('div');row.className='todo-item'+(t.done?' done':'');const check=document.createElement('input');check.type='checkbox';check.checked=!!t.done;check.setAttribute('aria-label',`${t.text} 완료`);check.addEventListener('change',()=>{t.done=check.checked;persist();renderTodos()});const label=document.createElement('span');label.className='todo-text';label.textContent=t.text;const del=document.createElement('button');del.className='delete-btn';del.textContent='×';del.setAttribute('aria-label',`${t.text} 삭제`);del.addEventListener('click',()=>{state.todos=state.todos.filter(item=>item.id!==t.id);persist();renderTodos()});row.append(check,label,del);list.append(row)})}
$('#todo-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#todo-input');const text=input.value.trim();if(!text)return;state.todos.unshift({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),text,done:false});input.value='';persist();renderTodos()});renderTodos();
$('#notes').value=state.notes||'';$('#notes').addEventListener('input',e=>{state.notes=e.target.value;persist();$('#save-status').textContent='저장됨'});
let month=new Date(),selected=new Date();month.setDate(1);
function renderCalendar(){const year=month.getFullYear(),m=month.getMonth();$('#month-label').textContent=`${year}년 ${m+1}월`;const grid=$('#calendar-grid');grid.replaceChildren();for(let i=0;i<new Date(year,m,1).getDay();i++)grid.append(document.createElement('span'));const today=dateKey(new Date());for(let day=1;day<=new Date(year,m+1,0).getDate();day++){const d=new Date(year,m,day),k=dateKey(d),b=document.createElement('button');b.textContent=day;b.setAttribute('aria-label',`${m+1}월 ${day}일`);if(k===today)b.classList.add('today');if(k===dateKey(selected))b.classList.add('selected');if(state.events[k]?.length)b.classList.add('has-event');b.addEventListener('click',()=>{selected=d;renderCalendar()});grid.append(b)}renderEvents()}
function renderEvents(){const k=dateKey(selected);$('#selected-date').textContent=`${selected.getMonth()+1}월 ${selected.getDate()}일 일정`;const list=$('#event-list');list.replaceChildren();(state.events[k]||[]).forEach((event,i)=>{const row=document.createElement('div');row.className='event-item';const span=document.createElement('span');span.textContent='✦ '+event;const del=document.createElement('button');del.className='delete-btn';del.textContent='×';del.setAttribute('aria-label',`${event} 삭제`);del.onclick=()=>{state.events[k].splice(i,1);persist();renderCalendar()};row.append(span,del);list.append(row)})}
$('#prev-month').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('#next-month').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};$('#event-form').onsubmit=e=>{e.preventDefault();const input=$('#event-input'),text=input.value.trim();if(!text)return;const k=dateKey(selected);(state.events[k]??=[]).push(text);input.value='';persist();renderCalendar()};renderCalendar();
function renderLinks(){const list=$('#link-list');list.replaceChildren();state.links.forEach((item,i)=>{const row=document.createElement('div');row.className='link-item';const a=document.createElement('a');a.textContent='↗  '+item.title;a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';const del=document.createElement('button');del.className='delete-btn';del.textContent='×';del.setAttribute('aria-label',`${item.title} 삭제`);del.onclick=()=>{state.links.splice(i,1);persist();renderLinks()};row.append(a,del);list.append(row)})}
$('#link-form').onsubmit=e=>{e.preventDefault();const title=$('#link-title').value.trim(),raw=$('#link-url').value.trim();let url;try{url=new URL(raw);if(!['https:','http:'].includes(url.protocol))return}catch{return}if(!title)return;state.links.push({title,url:url.href});persist();renderLinks();e.target.reset()};renderLinks();
let duration=25*60,remaining=duration,endAt=0,timerId=null;
function renderTimer(){const sec=timerId?Math.max(0,Math.ceil((endAt-Date.now())/1000)):remaining;$('#timer-display').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('#timer-progress').style.width=`${(1-sec/duration)*100}%`;$('#timer-toggle').textContent=timerId?'일시정지':'시작';document.title=timerId?`${$('#timer-display').textContent} · 도현의 작은 방`:'도현의 작은 방';if(timerId&&sec===0){clearInterval(timerId);timerId=null;remaining=0;renderTimer();$('#timer-mode').textContent='시간이 다 됐어요 ✦';if('Notification'in window&&Notification.permission==='granted')new Notification('집중 시간이 끝났어요!')}}
$('#timer-toggle').onclick=()=>{if(timerId){remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));clearInterval(timerId);timerId=null}else{if(remaining===0)remaining=duration;endAt=Date.now()+remaining*1000;timerId=setInterval(renderTimer,250)}renderTimer()};$('#timer-reset').onclick=()=>{clearInterval(timerId);timerId=null;remaining=duration;$('#timer-mode').textContent='집중 시간';renderTimer()};$$('[data-minutes]').forEach(b=>b.onclick=()=>{clearInterval(timerId);timerId=null;duration=Number(b.dataset.minutes)*60;remaining=duration;$('#timer-mode').textContent=duration===300?'잠깐 쉬어가기':'집중 시간';$$('[data-minutes]').forEach(x=>x.classList.toggle('selected',x===b));renderTimer()});renderTimer();
// An original, short piano-like melody synthesized locally by Web Audio.
let audioCtx,master,musicTimer,step=0,fileAudio,fileURL;
const melody=[['E5','C5'],[],['G5'],['E5'],['D5','B4'],[],['C5'],['G4'],['A4','F4'],[],['C5'],['E5'],['D5','G4'],[],['B4'],['G4']];
const notes={C4:261.63,D4:293.66,E4:329.63,F4:349.23,G4:392,A4:440,B4:493.88,C5:523.25,D5:587.33,E5:659.25,F5:698.46,G5:783.99};
function note(freq,when){const osc=audioCtx.createOscillator(),harm=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';harm.type='triangle';osc.frequency.value=freq;harm.frequency.value=freq*2;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(.16,when+.012);gain.gain.exponentialRampToValueAtTime(.0001,when+1.25);osc.connect(gain);harm.connect(gain);gain.connect(master);osc.start(when);harm.start(when);osc.stop(when+1.3);harm.stop(when+1.3)}
function playPhrase(){if(!audioCtx)return;const now=audioCtx.currentTime+.05;for(let i=0;i<4;i++){melody[(step+i)%melody.length].forEach(n=>note(notes[n],now+i*.32))}step=(step+4)%melody.length}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}if(fileAudio)fileAudio.pause();if(audioCtx)audioCtx.suspend();$('#music-toggle').textContent='▶ 재생';$('.music-card').classList.remove('playing')}
async function startMusic(){if(fileAudio){fileAudio.volume=Number($('#volume').value)/100;await fileAudio.play()}else{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();master??=audioCtx.createGain();master.gain.value=Number($('#volume').value)/100*.35;master.connect(audioCtx.destination);await audioCtx.resume();playPhrase();musicTimer=setInterval(playPhrase,1280)}$('#music-toggle').textContent='Ⅱ 일시정지';$('.music-card').classList.add('playing')}
$('#music-toggle').onclick=()=>{if(musicTimer||(fileAudio&&!fileAudio.paused))stopMusic();else startMusic().catch(()=>{stopMusic();$('#track-name').textContent='음악을 재생할 수 없어요'})};$('#volume').oninput=e=>{if(master)master.gain.value=Number(e.target.value)/100*.35;if(fileAudio)fileAudio.volume=Number(e.target.value)/100};$('#audio-file').onchange=e=>{const file=e.target.files?.[0];if(!file)return;stopMusic();if(fileURL)URL.revokeObjectURL(fileURL);fileURL=URL.createObjectURL(file);fileAudio=new Audio(fileURL);fileAudio.loop=true;fileAudio.volume=Number($('#volume').value)/100;$('#track-name').textContent=file.name};
